AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: false
  # Enabled: true
  # EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

#################

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - '*.gemspec'

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Layout/SpaceAroundBlockParameters:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Security/Eval:
  Enabled: false

Style/Alias:
  Enabled: false

# Layout/SpaceBeforeBlockBraces:
#   Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/MethodName:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceAfterNot:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
